### ISSUE TITLE
Command `run_all` Cooja error (`could not load plugin class: VisualizerScreenshot`)

### ISSUE THREAD

**Issue by faithphd** [dhondta/rpl-attacks#43]
<img width="884" alt="Screen Shot 2019-04-02 at 23 01 33" src="https://user-images.githubusercontent.com/49210583/55432370-65ef8a80-559b-11e9-9751-db541c61f8c1.png">

Hi everyone, first of all, I would like to say thank you to the owners of this framework.
And I want to ask a question about rpl-attack-framework.

I installed rpl-attack-framework and after that I tried to make a simulation.
I ran `prepare sample-attacks` command successfully
I ran `make_all sample-attacks` command successfully 
but when I tried to run `run_all sample-attacks` command I got a cooja error - `could not load plugin class: visualizerscreenshot`

you can see all the details in the attached png file.
if anyone can help me, I will be very happy.
thank you

**Comment by dhondta** [comment]
Hi @faithphd ,
Thank you for mentioning this issue.
Are you using the virtual appliance provided with the `Vagrantfile` ?
What is your configuration ?
Please provide the outputs of these commands :
- `uname -a`
- `java --version`

Did you run the `setup` command before trying `run` ?

**Comment by faithphd** [comment]
hi dhonta,

I am using the virtual appliance provided with the `Vagrantfile`.

The commands that I ran in my first experiment :
- `prepare sample-attacks`
- `make_all sample-attacks`
- `run_all sample-attacks`

The commands that I ran in my second experiment:
- `setup`
- `prepare sample-attacks`
- `make_all sample-attacks`
- `run_all sample-attacks`

Both in my first experiment and the second experiment i got the same errors (which are listed in the attached png file above).

My configuration details are listed below:

```
user@rpl-attacks-framework:~/rpl-attacks$ java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1ubuntu0.18.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

user@rpl-attacks-framework:~/rpl-attacks$ uname -a
Linux rpl-attacks-framework 4.15.0-38-generic #41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by dhondta** [comment]
OK, I think I figured out your problem ;

**Explanation**: You're possibly running the box as it was when I boxed it for Vagrant. It may still contain a bug I fixed later without re-boxing the framework (because this is a time-consuming process).

**Check**: If the command `versions` gives something less than `1.3.0[...]`, you are very likely to have such bug in your appliance.

**Solution**: Execute the command `update` to fix it. Then retry your experiments.

Please tell me if it solved your issue...

**Comment by faithphd** [comment]
thank you dhonta,
but when I run update command I get this errors. you can see the errors from screenshot.
i get this error when i run update command from the rpl attacks framework icon.(terminal which is opened when i click rpl framework icon on the desktop)

<img width="803" alt="Screen Shot 2019-04-10 at 22 26 22" src="https://user-images.githubusercontent.com/49210583/55907638-f8b5a800-5bdf-11e9-96e8-3d80ceee3a7a.png">

**Comment by faithphd** [comment]
hi dhonta , I run update command in terminal.(i opened a new terminal window without using rpl attack framewrok icon.)
I didnt get any error when i execute update command but it runs only 10 or 15 seconds (what is the average time for update?)
after that the framework restarted

I still get the same errors.(Command `run_all` Cooja error (`could not load plugin class: VisualizerScreenshot`)

**Comment by dhondta** [comment]
OK, I will take a look at this deeper.
`VisualizerScreenshot` is my custom plugin for Cooja made to collect screenshots from the builtin plugin `Visualizer`. If something fails with this, it could be because of a regression bug in Java if it was updated/upgraded or because something fails to copy/modify during the execution of the `setup` command inside the framework.
Did you try to update/upgrade Java in your VM ?

**Comment by dhondta** [comment]
Hi @faithphd ,

Weird... I just tried and it works fine for me.
My sequence of actions :
- `vagrant up`
- Then, inside the VM : 
  - `prepare sample-attacks`
  - `make_all sample-attacks.json`
  - `run_all sample-attacks.json`

<details>
<summary><code>run_all</code></summary>

![run_all](https://user-images.githubusercontent.com/9108102/55931856-689b5100-5c27-11e9-847b-ae199e93333f.png)

</details>

<details>
<summary>Results</summary>

![results](https://user-images.githubusercontent.com/9108102/55931869-76e96d00-5c27-11e9-823f-dccef2912dcf.png)

</details>

**Comment by dhondta** [comment]
OK, for now, could you try this sequence and post the trace, please ?
- `loglevel debug`
- `update`
- `run_all`

**Note**:
- I didn't see any prompt for sudo in your last screenshot of `setup`, it should not happen with the default VM.
- If we don't manage to get it working, it could be useful either to reinstall the VM with the `Vagrantfile` or, inside your current VM, to remove `rpl-attacks` folder and reclone the Git repo.
